services:
  - type: web
    name: sentinel-soc-backend
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: sentinel-soc-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://sentinel-soc-nine.vercel.app,http://localhost:5173,http://127.0.0.1:5173
databases:
  - name: sentinel-soc-db
    plan: free
